import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/store/theme-provider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "OmicsML",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="og:title" content="OmicsML" />
        <meta
          name="og:image"
          content="https://cdn.servatom.com/external/OmicsML/thumbnail.jpeg"
        ></meta>
        <meta
          name="og:description"
          content="Machine Learning for Omics Data Analysis Simplified"
        ></meta>
      </head>
      <body className={`flex flex-row`}>
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
